### ISSUE TITLE
Hitslop typedef error

### ISSUE THREAD

**Issue by dancixx** [WrathChaos/react-native-bouncy-checkbox#64]
Hi!

If I redefine the `TouchableComponent` property with the `Pressable` component then I would like to set the `hitSlop` but I got an error.

`Type 'number' is not assignable to type 'Insets | undefined'`
When we use `Pressable` I think the `hitSlop` can be a `number` type too.

```
<BouncyCheckbox 
   onPress={() => {}} 
   disableText={true} 
   TouchableComponent={Pressable}
   hitSlop={12}
/>
```

**Comment by WrathChaos** [comment]
Hello @dancixx ,

<img width="564" alt="CleanShot 2021-10-09 at 16 39 50@2x" src="https://user-images.githubusercontent.com/6813862/136660168-b60a74e5-0b3c-4e83-a611-dd29d11fb788.png">


As you can see `hitSlop` prop requires the `Insets` type not `number`. You should use it actually. If you really want to use a number one, you should write your own `Touchable` component and accepts a `number` prop hitslop parameter and then use your own component into the `TouchableComponent` prop. Otherwise, you should use the right type.
